name: Test, build and deploy
on: [push]
jobs:

  generate-ciphers:
    runs-on: ubuntu-latest
    container:
      image: centos:8
      volumes: 
        - ${{ github.workspace }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - shell: bash  
        run: |
          dnf install openssl python3 -y
          python3 ciphers2json.py

      - name: Upload generated cipher list
        uses: actions/upload-artifact@v1
        with:
          name: ciphers
          path: ciphers.json

  test-script:
    runs-on: ubuntu-latest
    container: centos:8
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - shell: bash
        run: |
          dnf install openssl python3 wget -y
          python3 test-testls.py
          chmod +x no-le-or-systemd-testls.sh
          ./no-le-or-systemd-testls.sh

  test-site:
    needs: generate-ciphers
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Download cipher list
      uses: actions/download-artifact@v1
      with:
        name: ciphers
        
    - shell: bash
      run: |
        mkdir -p site/_data site/_includes
        python3 create-script-include.py
        python3 ciphers2json.py
        mv ciphers/ciphers.json site/ciphers.json
        cd site
        jekyll build
 
  build-and-deploy:
    needs: [test-script, test-site, generate-ciphers]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Download cipher list
      uses: actions/download-artifact@v1
      with:
        name: ciphers

    - shell: bash
      run: |
        mkdir -p ${{ github.workspace }}/site/_data/ ${{ github.workspace }}/site/_includes/
        mv ciphers/ciphers.json ${{ github.workspace }}/site/_data/

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: site # The folder the action should deploy.
        BUILD_SCRIPT: python3 create-script-include.py # The build script the action should run prior to deploying.
